name: neyyar_heritage
description: A new Flutter Neyyar Heritage project.

version: 2.0.0+2

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.11.0

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  percent_indicator: ^4.2.3
  intl: ^0.20.2
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


